### ISSUE TITLE
Applying homodirectional gradients for cloning?

### ISSUE THREAD

**Issue by laphisboy** [TY424/AbsGS#5]
From my understanding of your work, applying homodirectional gradients for cloning could potentially improve reconstruction quality. Do you have any empirical results or insights on this you could share?

**Comment by TY424** [comment]
Thank you for your interest in our work. The strategy of cloning in the original position might not be very effective, especially in cases where gradient collisions are significant. This is because the position gradients are small and difficult to optimize. It might be worth exploring more effective new Gaussian generation strategies.

**Comment by laphisboy** [comment]
Thank you for your answer!
